//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteLogApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteLogApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /* jQuery v1.6.4 http://jquery.com/ | http://jquery.org/license */
        ///(function(d,b){function C(b){return a.isWindow(b)?b:b.nodeType===9?b.defaultView||b.parentWindow:!1}function gb(b){if(!B[b]){var g=c.body,d=a(&quot;&lt;&quot;+b+&quot;&gt;&quot;).appendTo(g),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){f||(f=c.createElement(&quot;iframe&quot;),f.frameBorder=f.width=f.height=0),g.appendChild(f);if(!m||!f.createElement)m=(f.contentWindow||f.contentDocument).document,m.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function ($, window, undefined) {
        ///    /// &lt;param name=&quot;$&quot; type=&quot;jQuery&quot; /&gt;
        ///    &quot;use strict&quot;;
        ///
        ///    if (typeof ($.signalR) !== &quot;function&quot;) {
        ///        throw new Error(&quot;SignalR: SignalR is not loaded. Please ensure jquery.signalR-x.js is referenced before ~/signalr/js.&quot;);
        ///    }
        ///
        ///    var signalR = $.signalR;
        ///
        ///    function makeProxyCallback(hub, callback) {
        ///        return function () {
        ///            // Call the client hub method
        ///            callback.apply(hub, $.makeArray(arguments));
        ///        };
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string client_source {
            get {
                return ResourceManager.GetString("client_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon console {
            get {
                object obj = ResourceManager.GetObject("console", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-size: 12px;
        ///            padding: 0px;
        ///            margin: 0;
        ///            font-family: &quot;Microsoft Yahei&quot;,Helvetica,Arial,&quot;Hiragino Sans GB&quot;,&quot;微软雅黑&quot;,STHeiti,&quot;华文细黑&quot;,sans-serif;
        ///        }
        ///
        ///        .log {
        ///            color: #909399;
        ///        }
        ///
        ///        .info {
        ///            color: #409EFF;
        ///        }
        ///
        ///        .warn {
        ///          [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*!
        /// * jQuery JavaScript Library v1.6.4
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Mon Sep 12 18:54:48 2011 -0400
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window.document,
        ///	navigat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_1_6_4 {
            get {
                return ResourceManager.GetString("jquery_1_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*! jQuery v1.6.4 http://jquery.com/ | http://jquery.org/license */
        ///(function(a,b){function cu(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cr(a){if(!cg[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){ch||(ch=c.createElement(&quot;iframe&quot;),ch.frameBorder=ch.width=ch.height=0),b.appendChild(ch);if(!ci||!ch.createElement)ci=(ch.contentWindow||ch.contentDocument).document,ci.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_1_6_4_min {
            get {
                return ResourceManager.GetString("jquery_1_6_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        ///* This file has been generated to support Visual Studio IntelliSense.
        ///* You should not use this file at runtime inside the browser--it is only
        ///* intended to be used only for design-time IntelliSense.  Please use the
        ///* standard jQuery library for all production use.
        ///*
        ///* Comment version: 1.6.4
        ///*/
        ///
        ////*!
        ///* jQuery JavaScript Library v1.6.4
        ///* http://jquery.com/
        ///*
        ///* Distributed in whole under the terms of the MIT
        ///*
        ///* Copyright 2010, John Resig
        ///*
        ///* Permission is hereby granted, free of charge, to any person obtai [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_1_6_4_vsdoc {
            get {
                return ResourceManager.GetString("jquery_1_6_4_vsdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /* jquery.signalR.core.js */
        ////*global window:false */
        ////*!
        /// * ASP.NET SignalR JavaScript Library 2.4.0
        /// * http://signalr.net/
        /// *
        /// * Copyright (c) .NET Foundation. All rights reserved.
        /// * Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
        /// *
        /// */
        ///
        ////// &lt;reference path=&quot;Scripts/jquery-1.6.4.js&quot; /&gt;
        ////// &lt;reference path=&quot;jquery.signalR.version.js&quot; /&gt;
        ///(function ($, window, undefined) {
        ///
        ///    var resources = {
        ///        nojQuery: &quot;jQuery was not f [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_signalR_2_4_0 {
            get {
                return ResourceManager.GetString("jquery_signalR_2_4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*!
        /// * ASP.NET SignalR JavaScript Library 2.4.0
        /// * http://signalr.net/
        /// *
        /// * Copyright (c) .NET Foundation. All rights reserved.
        /// * Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
        /// *
        /// */
        ///(function(n,t,i){function w(t,i){var u,f;if(n.isArray(t)){for(u=t.length-1;u&gt;=0;u--)f=t[u],n.type(f)===&quot;string&quot;&amp;&amp;r.transports[f]||(i.log(&quot;Invalid transport: &quot;+f+&quot;, removing it from the transports list.&quot;),t.splice(u,1));t.length===0&amp;&amp;(i.log(&quot;No transports remain wi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_signalR_2_4_0_min {
            get {
                return ResourceManager.GetString("jquery_signalR_2_4_0_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_AspNet_SignalR_Core {
            get {
                object obj = ResourceManager.GetObject("Microsoft_AspNet_SignalR_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_AspNet_SignalR_Owin {
            get {
                object obj = ResourceManager.GetObject("Microsoft_AspNet_SignalR_Owin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_Cors {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_Cors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_Diagnostics {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_Diagnostics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_FileSystems {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_FileSystems", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_Host_HttpListener {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_Host_HttpListener", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_Hosting {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_Hosting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_Security {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_Security", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_Owin_StaticFiles {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Owin_StaticFiles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Owin {
            get {
                object obj = ResourceManager.GetObject("Owin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] System_Web_Cors {
            get {
                object obj = ResourceManager.GetObject("System_Web_Cors", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
